"""常量定义"""

# 平台类型
PLATFORM_DOUYIN = "douyin"
PLATFORM_BILIBILI = "bilibili"
PLATFORM_TWITCH = "twitch"
PLATFORM_YOUTUBE = "youtube"
PLATFORM_HUYA = "huya"
PLATFORM_DOUYU = "douyu"
PLATFORM_KICK = "kick"
PLATFORM_TIKTOK = "tiktok"
PLATFORM_AFREECA = "afreeca"
PLATFORM_GENERIC = "generic"

SUPPORTED_PLATFORMS = [
    PLATFORM_DOUYIN,
    PLATFORM_BILIBILI,
    PLATFORM_TWITCH,
    PLATFORM_YOUTUBE,
    PLATFORM_HUYA,
    PLATFORM_DOUYU,
    PLATFORM_KICK,
    PLATFORM_TIKTOK,
    PLATFORM_AFREECA,
    PLATFORM_GENERIC,
]

# 录制状态
STATUS_IDLE = "idle"
STATUS_CHECKING = "checking"
STATUS_RECORDING = "recording"
STATUS_PROCESSING = "processing"
STATUS_ERROR = "error"

# 合并信心度阈值
MERGE_CONFIDENCE_HIGH = 0.7
MERGE_CONFIDENCE_LOW = 0.4

# 文件大小限制
MAX_FILE_SIZE_MB = 10240
SPLIT_SIZE_MB_DEFAULT = 2048
SPLIT_DURATION_MINUTES_DEFAULT = 60

# 超时设置
CHECK_TIMEOUT_SECONDS = 30
RECORD_TIMEOUT_SECONDS = 3600
PROCESS_TIMEOUT_SECONDS = 1800

# 用户层级
TIER_FREE = "free"
TIER_PRO = "pro"
TIER_TEAM = "team"

# 配额限制
QUOTA_FREE_CLIPS_PER_DAY = 3
QUOTA_PRO_CLIPS_PER_DAY = 50
QUOTA_FREE_MAX_MODELS = 3
QUOTA_PRO_MAX_MODELS = 20
